[package]
name = "huber"
version = "0.1.0"
authors = ["David Ko <innobead@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
log = "0.4"
fern = "0.5"
lazy_static = "1.4.0"
anyhow = "1.0"
thiserror = "1.0"
dirs = "3.0.1"