name: Build

on:
  workflow_dispatch:
    inputs:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-linux:
    name: Build for Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: make test

      - name: Build all artifacts
        run: make build

  build-linux-aarch64:
    name: Build for Linux aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2.0.5
          name: Setup,Test,Build
          with:
            arch: aarch64
            distro: ubuntu20.04
            githubToken: ${{ github.token }}
            run: |
              uname -a
              make setup-dev
              make test
              make build

  build-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: source ~/.bashrc && make test

      - name: Build all artifacts
        run: source ~/.bashrc && make build
