name: Build

on:
  workflow_dispatch:
    inputs:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: make test

      - name: Build all artifacts
        run: make build

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup build environment
        run: make setup-dev

      - name: Run tests
        run: source ~/.bashrc && make test

      - name: Build all artifacts
        run: source ~/.bashrc && make build
