name: Build

on:
  workflow_dispatch:
    inputs:

jobs:
  build-linux-x86_64:
    name: Build - linux x86_64
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: extractions/setup-just@v1

    - name: Setup build environment
      run: just setup-dev

    - name: Run tests
      run: just test

    - name: Build artifacts
      run: just build

  build-macos:
    name: Build - macos
    runs-on: macos-12
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup build environment
      run: just setup-dev

    - name: Run tests
      run: |
        source ~/.bashrc
        just test

    - name: Build artifacts
      run: |
        source ~/.bashrc
        just build

  build-windows:
    name: Build - windows
    runs-on: windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup build environment
      run: ./hack/windows/setup-dev.ps1

    - name: Run tests
      run: cargo test

    - name: Build artifacts
      run: cargo build