name: Generate and Suggest Changes

on:
  pull_request:
    paths:
      - 'crates/generator/src/pkg/*.rs'

jobs:
  generate-and-suggest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install Development Packages
      run: sudo apt-get update && sudo apt-get install -y libssl-dev libarchive-dev

    - name: cargo install
      run: cargo install just

    - name: Run just generate
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} just generate

    - uses: parkerbxyz/suggest-changes@v1
      with:
        comment: 'suggested changes from `generator` output.'
